// Code generated by ./stubgen; DO NOT EDIT.
//
// This file is regenerated from internal/db/storage.go's Storage interface
// each time //go:generate runs. To regenerate after changing the interface
// or implementing a method elsewhere in this package:
//
//	go generate ./internal/db/pgstore
//
// or, from this directory:
//
//	go run ./stubgen
//
// Methods implemented in store.go, open.go, or inherited from the
// embedded *sql.DB are skipped via stubgen/main.go's alreadyImplemented
// allow-list. Phase 4 work moves a method by:
//
//  1. Adding the method name to alreadyImplemented in stubgen/main.go,
//  2. Writing the real implementation in a new pgstore .go file, and
//  3. Re-running go generate so this file no longer carries the stub.

package pgstore

import (
	"context"
	"iter"
	"time"

	"go.kenn.io/kata/internal/db"
)

// Compile-time check that *Store satisfies db.Storage. Phase 4 replaces
// stubs in this file with real query implementations elsewhere in the
// package; the assertion stays here so a missing or mistyped method is
// caught at build time.
var _ db.Storage = (*Store)(nil)

func (s *Store) AcquireClaim(_ context.Context, _ db.AcquireClaimParams) (db.LeaseResult, error) {
	return db.LeaseResult{}, ErrNotImplementedPhase3
}

func (s *Store) ActiveFederationQuarantine(_ context.Context, _ int64, _ db.FederationQuarantineDirection) (db.FederationQuarantine, error) {
	return db.FederationQuarantine{}, ErrNotImplementedPhase3
}

func (s *Store) ActiveFederationQuarantinesByProject(_ context.Context, _ int64) ([]db.FederationQuarantine, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) AddLabel(_ context.Context, _ int64, _ string, _ string) (db.IssueLabel, error) {
	return db.IssueLabel{}, ErrNotImplementedPhase3
}

func (s *Store) AddLabelAndEvent(_ context.Context, _ int64, _ db.LabelEventParams) (db.IssueLabel, db.Event, error) {
	return db.IssueLabel{}, db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) AdoptProjectIntoFederation(_ context.Context, _ db.AdoptProjectIntoFederationParams) (db.AdoptProjectIntoFederationResult, error) {
	return db.AdoptProjectIntoFederationResult{}, ErrNotImplementedPhase3
}

func (s *Store) AdvanceFederationPullCursor(_ context.Context, _ int64, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) AdvanceFederationPushCursor(_ context.Context, _ int64, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) AliasByID(_ context.Context, _ int64) (db.ProjectAlias, error) {
	return db.ProjectAlias{}, ErrNotImplementedPhase3
}

func (s *Store) AliasByIdentity(_ context.Context, _ string) (db.ProjectAlias, error) {
	return db.ProjectAlias{}, ErrNotImplementedPhase3
}

func (s *Store) ApplyClaimStatus(_ context.Context, _ int64, _ string, _ db.ClaimStatus) error {
	return ErrNotImplementedPhase3
}

func (s *Store) AttachAlias(_ context.Context, _ int64, _ string, _ string, _ string) (db.ProjectAlias, error) {
	return db.ProjectAlias{}, ErrNotImplementedPhase3
}

func (s *Store) AuthorizeFederationToken(_ context.Context, _ string, _ int64, _ string) (db.FederationEnrollment, error) {
	return db.FederationEnrollment{}, ErrNotImplementedPhase3
}

func (s *Store) BatchProjectStats(_ context.Context) (map[int64]db.ProjectStats, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) BlockNumbersByIssues(_ context.Context, _ int64, _ []int64) (map[int64][]int64, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) BlockedByNumbersByIssues(_ context.Context, _ int64, _ []int64) (map[int64][]int64, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) CheckClaimGate(_ context.Context, _ db.ClaimGateParams) error {
	return ErrNotImplementedPhase3
}

func (s *Store) ChildCountsByParents(_ context.Context, _ int64, _ []int64) (map[int64]db.ChildCounts, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ChildrenOfIssue(_ context.Context, _ int64, _ int64) ([]db.Issue, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ClaimOwner(_ context.Context, _ int64, _ string, _ bool) (db.ClaimResult, error) {
	return db.ClaimResult{}, ErrNotImplementedPhase3
}

func (s *Store) ClaimStatus(_ context.Context, _ int64, _ string, _ time.Time) (db.ClaimStatus, error) {
	return db.ClaimStatus{}, ErrNotImplementedPhase3
}

func (s *Store) ClaimStatusReadOnly(_ context.Context, _ int64, _ string, _ time.Time) (db.ClaimStatus, error) {
	return db.ClaimStatus{}, ErrNotImplementedPhase3
}

func (s *Store) ClaimStatusRefreshError(_ context.Context, _ int64, _ string) (db.ClaimStatusRefreshError, error) {
	return db.ClaimStatusRefreshError{}, ErrNotImplementedPhase3
}

func (s *Store) ClearClaimStatusRefreshError(_ context.Context, _ int64, _ string) error {
	return ErrNotImplementedPhase3
}

func (s *Store) ClearFederationSyncError(_ context.Context, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) CloseIssue(_ context.Context, _ int64, _ string, _ string, _ string, _ []db.Evidence) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) CloseIssueWithEvents(_ context.Context, _ int64, _ string, _ string, _ string, _ []db.Evidence) (db.Issue, []db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) CommentBodyByID(_ context.Context, _ int64) (string, error) {
	return "", ErrNotImplementedPhase3
}

func (s *Store) CommentsByIssue(_ context.Context, _ int64) ([]db.Comment, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) CountActiveFederationEnrollments(_ context.Context, _ int64) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) CountLiveClaims(_ context.Context, _ int64) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) CountPendingClaims(_ context.Context, _ int64) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) CreateAPIToken(_ context.Context, _ db.CreateAPITokenParams) (db.APIToken, db.Event, error) {
	return db.APIToken{}, db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) CreateComment(_ context.Context, _ db.CreateCommentParams) (db.Comment, db.Event, error) {
	return db.Comment{}, db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) CreateFederationEnrollment(_ context.Context, _ db.CreateFederationEnrollmentParams) (db.CreatedFederationEnrollment, error) {
	return db.CreatedFederationEnrollment{}, ErrNotImplementedPhase3
}

func (s *Store) CreateIssue(_ context.Context, _ db.CreateIssueParams) (db.Issue, db.Event, error) {
	return db.Issue{}, db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) CreateLink(_ context.Context, _ db.CreateLinkParams) (db.Link, error) {
	return db.Link{}, ErrNotImplementedPhase3
}

func (s *Store) CreateLinkAndEvent(_ context.Context, _ db.CreateLinkParams, _ db.LinkEventParams) (db.Link, db.Event, error) {
	return db.Link{}, db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) CreateProject(_ context.Context, _ string) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) CreateProjectWithUID(_ context.Context, _ string, _ string) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) CreateRecurrence(_ context.Context, _ db.CreateRecurrenceIn) (db.Recurrence, error) {
	return db.Recurrence{}, ErrNotImplementedPhase3
}

func (s *Store) DeleteLinkAndEvent(_ context.Context, _ db.Link, _ db.LinkEventParams) (db.Event, error) {
	return db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) DeleteLinkByID(_ context.Context, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) DetachProjectAlias(_ context.Context, _ db.DetachAliasParams) (db.ProjectAlias, *db.Event, error) {
	return db.ProjectAlias{}, nil, ErrNotImplementedPhase3
}

func (s *Store) EditIssue(_ context.Context, _ db.EditIssueParams) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) EditIssueAtomic(_ context.Context, _ db.EditIssueAtomicParams) (db.EditIssueAtomicResult, error) {
	return db.EditIssueAtomicResult{}, ErrNotImplementedPhase3
}

func (s *Store) EnableFederationPush(_ context.Context, _ int64, _ int64) (db.FederationBinding, error) {
	return db.FederationBinding{}, ErrNotImplementedPhase3
}

func (s *Store) EnableProjectFederation(_ context.Context, _ int64, _ string) (db.FederationBinding, error) {
	return db.FederationBinding{}, ErrNotImplementedPhase3
}

func (s *Store) EnqueuePendingClaim(_ context.Context, _ db.PendingClaimParams) (db.PendingClaimRequest, error) {
	return db.PendingClaimRequest{}, ErrNotImplementedPhase3
}

func (s *Store) EnsureSystemProject(_ context.Context) error {
	return ErrNotImplementedPhase3
}

func (s *Store) EventsAfter(_ context.Context, _ db.EventsAfterParams) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) EventsByUIDs(_ context.Context, _ int64, _ []string) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) EventsInWindow(_ context.Context, _ db.EventsInWindowParams) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ExpireTimedClaims(_ context.Context, _ time.Time, _ int) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ExpireTimedClaimsForProject(_ context.Context, _ int64, _ time.Time, _ int) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ExportComments(_ context.Context, _ db.ExportFilter) iter.Seq2[db.CommentExport, error] {
	return func(yield func(db.CommentExport, error) bool) {
		yield(db.CommentExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportEvents(_ context.Context, _ db.ExportFilter) iter.Seq2[db.EventExport, error] {
	return func(yield func(db.EventExport, error) bool) {
		yield(db.EventExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportFederationBindings(_ context.Context, _ db.ExportFilter) iter.Seq2[db.FederationBindingExport, error] {
	return func(yield func(db.FederationBindingExport, error) bool) {
		yield(db.FederationBindingExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportFederationEnrollments(_ context.Context, _ db.ExportFilter) iter.Seq2[db.FederationEnrollmentExport, error] {
	return func(yield func(db.FederationEnrollmentExport, error) bool) {
		yield(db.FederationEnrollmentExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportFederationQuarantine(_ context.Context, _ db.ExportFilter) iter.Seq2[db.FederationQuarantineExport, error] {
	return func(yield func(db.FederationQuarantineExport, error) bool) {
		yield(db.FederationQuarantineExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportFederationSyncStatus(_ context.Context, _ db.ExportFilter) iter.Seq2[db.FederationSyncStatusExport, error] {
	return func(yield func(db.FederationSyncStatusExport, error) bool) {
		yield(db.FederationSyncStatusExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportImportMappings(_ context.Context, _ db.ExportFilter) iter.Seq2[db.ImportMappingExport, error] {
	return func(yield func(db.ImportMappingExport, error) bool) {
		yield(db.ImportMappingExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportIssueClaims(_ context.Context, _ db.ExportFilter) iter.Seq2[db.IssueClaimExport, error] {
	return func(yield func(db.IssueClaimExport, error) bool) {
		yield(db.IssueClaimExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportIssueLabels(_ context.Context, _ db.ExportFilter) iter.Seq2[db.IssueLabelExport, error] {
	return func(yield func(db.IssueLabelExport, error) bool) {
		yield(db.IssueLabelExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportIssues(_ context.Context, _ db.ExportFilter) iter.Seq2[db.IssueExport, error] {
	return func(yield func(db.IssueExport, error) bool) {
		yield(db.IssueExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportLinks(_ context.Context, _ db.ExportFilter) iter.Seq2[db.LinkExport, error] {
	return func(yield func(db.LinkExport, error) bool) {
		yield(db.LinkExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportMeta(_ context.Context) iter.Seq2[db.MetaKV, error] {
	return func(yield func(db.MetaKV, error) bool) {
		yield(db.MetaKV{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportPendingClaimRequests(_ context.Context, _ db.ExportFilter) iter.Seq2[db.PendingClaimRequestExport, error] {
	return func(yield func(db.PendingClaimRequestExport, error) bool) {
		yield(db.PendingClaimRequestExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportProjectAliases(_ context.Context, _ db.ExportFilter) iter.Seq2[db.AliasExport, error] {
	return func(yield func(db.AliasExport, error) bool) {
		yield(db.AliasExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportProjects(_ context.Context, _ db.ExportFilter) iter.Seq2[db.ProjectExport, error] {
	return func(yield func(db.ProjectExport, error) bool) {
		yield(db.ProjectExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportPurgeLog(_ context.Context, _ db.ExportFilter) iter.Seq2[db.PurgeLogExport, error] {
	return func(yield func(db.PurgeLogExport, error) bool) {
		yield(db.PurgeLogExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportRecurrences(_ context.Context, _ db.ExportFilter) iter.Seq2[db.RecurrenceExport, error] {
	return func(yield func(db.RecurrenceExport, error) bool) {
		yield(db.RecurrenceExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) ExportSequences(_ context.Context) iter.Seq2[db.SequenceExport, error] {
	return func(yield func(db.SequenceExport, error) bool) {
		yield(db.SequenceExport{}, ErrNotImplementedPhase3)
	}
}

func (s *Store) FederationBindingByProject(_ context.Context, _ int64) (db.FederationBinding, error) {
	return db.FederationBinding{}, ErrNotImplementedPhase3
}

func (s *Store) FederationSyncStatusByProject(_ context.Context, _ int64) (db.FederationSyncStatus, error) {
	return db.FederationSyncStatus{}, ErrNotImplementedPhase3
}

func (s *Store) ForceReleaseClaim(_ context.Context, _ db.ForceReleaseClaimParams) (db.LeaseResult, error) {
	return db.LeaseResult{}, ErrNotImplementedPhase3
}

func (s *Store) GetRecurrenceByID(_ context.Context, _ int64) (db.Recurrence, error) {
	return db.Recurrence{}, ErrNotImplementedPhase3
}

func (s *Store) GetRecurrenceByUID(_ context.Context, _ string) (db.Recurrence, error) {
	return db.Recurrence{}, ErrNotImplementedPhase3
}

func (s *Store) HardDeleteProject(_ context.Context, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) HasLabel(_ context.Context, _ int64, _ string) (bool, error) {
	return false, ErrNotImplementedPhase3
}

func (s *Store) ImportBatch(_ context.Context, _ db.ImportBatchParams) (db.ImportBatchResult, []db.Event, error) {
	return db.ImportBatchResult{}, nil, ErrNotImplementedPhase3
}

func (s *Store) ImportMappingBySource(_ context.Context, _ int64, _ string, _ string, _ string) (db.ImportMapping, error) {
	return db.ImportMapping{}, ErrNotImplementedPhase3
}

func (s *Store) ImportMappingsByProjectSource(_ context.Context, _ int64, _ string) ([]db.ImportMapping, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ImportReplay(_ context.Context, _ []db.ImportRecord, _ db.ImportOptions) error {
	return ErrNotImplementedPhase3
}

func (s *Store) IngestFederationEvents(_ context.Context, _ db.FederationIngestParams) (db.FederationIngestResult, error) {
	return db.FederationIngestResult{}, ErrNotImplementedPhase3
}

func (s *Store) InsertCloseThrottledEvent(_ context.Context, _ int64, _ string, _ db.CloseThrottledPayload) (db.Event, error) {
	return db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) InsertRemoteEvent(_ context.Context, _ int64, _ db.RemoteEvent) (bool, error) {
	return false, ErrNotImplementedPhase3
}

func (s *Store) IssueByID(_ context.Context, _ int64) (db.Issue, error) {
	return db.Issue{}, ErrNotImplementedPhase3
}

func (s *Store) IssueByShortID(_ context.Context, _ int64, _ string, _ db.IncludeDeleted) (db.Issue, error) {
	return db.Issue{}, ErrNotImplementedPhase3
}

func (s *Store) IssueByUID(_ context.Context, _ string, _ db.IncludeDeleted) (db.Issue, error) {
	return db.Issue{}, ErrNotImplementedPhase3
}

func (s *Store) IssueUIDPrefixMatch(_ context.Context, _ string, _ int, _ db.IncludeDeleted) ([]db.Issue, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) LabelByEndpoints(_ context.Context, _ int64, _ string) (db.IssueLabel, error) {
	return db.IssueLabel{}, ErrNotImplementedPhase3
}

func (s *Store) LabelCounts(_ context.Context, _ int64) ([]db.LabelCount, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) LabelsByIssue(_ context.Context, _ int64) ([]db.IssueLabel, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) LabelsByIssues(_ context.Context, _ int64, _ []int64) (map[int64][]string, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) LabelsForIssue(_ context.Context, _ int64) ([]string, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) LatestAliasForProject(_ context.Context, _ int64) (db.AliasRow, bool, error) {
	return db.AliasRow{}, false, ErrNotImplementedPhase3
}

func (s *Store) LinkByEndpoints(_ context.Context, _ int64, _ int64, _ string) (db.Link, error) {
	return db.Link{}, ErrNotImplementedPhase3
}

func (s *Store) LinkByID(_ context.Context, _ int64) (db.Link, error) {
	return db.Link{}, ErrNotImplementedPhase3
}

func (s *Store) LinksByIssue(_ context.Context, _ int64) ([]db.Link, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListAPITokens(_ context.Context) ([]db.APIToken, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListAllIssues(_ context.Context, _ db.ListAllIssuesParams) ([]db.Issue, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListFederationBindings(_ context.Context) ([]db.FederationBinding, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListFederationEnrollments(_ context.Context) ([]db.FederationEnrollment, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListIssues(_ context.Context, _ db.ListIssuesParams) ([]db.Issue, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListPendingClaimRequests(_ context.Context, _ int64, _ int) ([]db.PendingClaimRequest, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListPendingClaimRequestsForIssue(_ context.Context, _ int64, _ string, _ int) ([]db.PendingClaimRequest, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListProjects(_ context.Context) ([]db.Project, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListProjectsIncludingArchived(_ context.Context) ([]db.Project, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ListRecurrencesByProject(_ context.Context, _ int64) ([]db.Recurrence, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) LookupIdempotency(_ context.Context, _ int64, _ string, _ time.Time) (*db.IdempotencyMatch, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) MarkClaimStatusRefreshError(_ context.Context, _ int64, _ string, _ int, _ string, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) MarkPendingClaimAttempt(_ context.Context, _ string, _ string, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) MaterializeFederatedProject(_ context.Context, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) MaterializeNext(_ context.Context, _ int64, _ string, _ string) (db.MaterializeNextOut, error) {
	return db.MaterializeNextOut{}, ErrNotImplementedPhase3
}

func (s *Store) MaxEventID(_ context.Context) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) MaxFederationBaselineEventID(_ context.Context, _ int64, _ int64) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) MaxLocalOriginEventID(_ context.Context, _ int64) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) MergeProjects(_ context.Context, _ db.MergeProjectsParams) (db.ProjectMergeResult, error) {
	return db.ProjectMergeResult{}, ErrNotImplementedPhase3
}

func (s *Store) MoveIssueProject(_ context.Context, _ db.MoveIssueProjectIn) (db.MoveIssueProjectOut, error) {
	return db.MoveIssueProjectOut{}, ErrNotImplementedPhase3
}

func (s *Store) OpenChildrenOf(_ context.Context, _ int64, _ int64, _ int) ([]db.Issue, int, error) {
	return nil, 0, ErrNotImplementedPhase3
}

func (s *Store) ParentNumbersByIssues(_ context.Context, _ int64, _ []int64) (map[int64]int64, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ParentOf(_ context.Context, _ int64) (db.Link, error) {
	return db.Link{}, ErrNotImplementedPhase3
}

func (s *Store) ParentShortIDsByIssues(_ context.Context, _ int64, _ []int64) (map[int64]string, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) PatchIssueMetadata(_ context.Context, _ db.PatchIssueMetadataIn) (db.PatchIssueMetadataOut, error) {
	return db.PatchIssueMetadataOut{}, ErrNotImplementedPhase3
}

func (s *Store) PatchProjectMetadata(_ context.Context, _ db.PatchProjectMetadataIn) (db.PatchProjectMetadataOut, error) {
	return db.PatchProjectMetadataOut{}, ErrNotImplementedPhase3
}

func (s *Store) PatchRecurrence(_ context.Context, _ db.PatchRecurrenceIn) (db.PatchRecurrenceOut, error) {
	return db.PatchRecurrenceOut{}, ErrNotImplementedPhase3
}

func (s *Store) PendingFederationPushEvents(_ context.Context, _ int64, _ string, _ int64, _ int) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) PendingFederationPushStats(_ context.Context, _ int64, _ string, _ int64) (int64, int64, error) {
	return 0, 0, ErrNotImplementedPhase3
}

func (s *Store) ProjectAliases(_ context.Context, _ int64) ([]db.ProjectAlias, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ProjectByID(_ context.Context, _ int64) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) ProjectByName(_ context.Context, _ string) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) ProjectByNameIncludingArchived(_ context.Context, _ string) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) ProjectByUID(_ context.Context, _ string) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) PurgeIssue(_ context.Context, _ int64, _ string, _ *string) (db.PurgeLog, error) {
	return db.PurgeLog{}, ErrNotImplementedPhase3
}

func (s *Store) PurgeResetCheck(_ context.Context, _ int64, _ int64) (int64, error) {
	return 0, ErrNotImplementedPhase3
}

func (s *Store) ReadyIssues(_ context.Context, _ int64, _ int, _ db.ReadyIssuesFilter) ([]db.Issue, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ReadyIssuesGlobal(_ context.Context, _ int) ([]db.ReadyGlobalIssue, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ReassignAlias(_ context.Context, _ int64, _ int64, _ string) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RecentSameMessageClose(_ context.Context, _ int64, _ int64, _ int64, _ string, _ string, _ time.Time) (*db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) RecentSiblingCloses(_ context.Context, _ int64, _ int64, _ int64, _ string, _ time.Time) ([]db.Event, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) RecordFederationQuarantine(_ context.Context, _ db.RecordFederationQuarantineParams) (db.FederationQuarantine, error) {
	return db.FederationQuarantine{}, ErrNotImplementedPhase3
}

func (s *Store) RecordFederationSyncError(_ context.Context, _ int64, _ error, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RecordFederationSyncPullStarted(_ context.Context, _ int64, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RecordFederationSyncPullSuccess(_ context.Context, _ int64, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RecordFederationSyncPushStarted(_ context.Context, _ int64, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RecordFederationSyncPushSuccess(_ context.Context, _ int64, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RecordFederationSyncReset(_ context.Context, _ int64, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RefreshProjectFederationBaseline(_ context.Context, _ int64, _ string) (db.FederationBinding, bool, error) {
	return db.FederationBinding{}, false, ErrNotImplementedPhase3
}

func (s *Store) RejectPendingClaim(_ context.Context, _ string, _ string, _ time.Time) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RelatedNumbersByIssues(_ context.Context, _ int64, _ []int64) (map[int64][]int64, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ReleaseClaim(_ context.Context, _ db.ReleaseClaimParams) (db.LeaseResult, error) {
	return db.LeaseResult{}, ErrNotImplementedPhase3
}

func (s *Store) RemoveLabel(_ context.Context, _ int64, _ string) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RemoveLabelAndEvent(_ context.Context, _ int64, _ db.LabelEventParams) (db.Event, error) {
	return db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) RemoveProject(_ context.Context, _ db.RemoveProjectParams) (db.Project, *db.Event, error) {
	return db.Project{}, nil, ErrNotImplementedPhase3
}

func (s *Store) RenameProject(_ context.Context, _ int64, _ string) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) RenewClaim(_ context.Context, _ db.RenewClaimParams) (db.LeaseResult, error) {
	return db.LeaseResult{}, ErrNotImplementedPhase3
}

func (s *Store) ReopenIssue(_ context.Context, _ int64, _ string) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) ResetFederatedProject(_ context.Context, _ int64, _ int64, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) ResetFederatedProjectIfNoPendingPush(_ context.Context, _ int64, _ int64, _ int64, _ string, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) ResolveAPIToken(_ context.Context, _ string) (db.APIToken, error) {
	return db.APIToken{}, ErrNotImplementedPhase3
}

func (s *Store) ResolvePendingClaim(_ context.Context, _ string, _ db.IssueClaim) error {
	return ErrNotImplementedPhase3
}

func (s *Store) RestoreIssue(_ context.Context, _ int64, _ string) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) RestoreProject(_ context.Context, _ int64, _ string) (db.Project, *db.Event, bool, error) {
	return db.Project{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) RevokeAPIToken(_ context.Context, _ int64, _ string) (db.APIToken, db.Event, error) {
	return db.APIToken{}, db.Event{}, ErrNotImplementedPhase3
}

func (s *Store) RevokeFederationEnrollment(_ context.Context, _ int64) error {
	return ErrNotImplementedPhase3
}

func (s *Store) SearchFTS(_ context.Context, _ int64, _ string, _ int, _ bool) ([]db.SearchCandidate, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) SearchFTSAny(_ context.Context, _ int64, _ string, _ int, _ bool) ([]db.SearchCandidate, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) ShortIDsByUIDs(_ context.Context, _ int64, _ []string) (map[string]string, error) {
	return nil, ErrNotImplementedPhase3
}

func (s *Store) SkipFederationQuarantine(_ context.Context, _ db.SkipFederationQuarantineParams) (db.FederationQuarantine, error) {
	return db.FederationQuarantine{}, ErrNotImplementedPhase3
}

func (s *Store) SoftDeleteIssue(_ context.Context, _ int64, _ string) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) SoftDeleteRecurrence(_ context.Context, _ int64, _ string) error {
	return ErrNotImplementedPhase3
}

func (s *Store) SystemProject(_ context.Context) (db.Project, error) {
	return db.Project{}, ErrNotImplementedPhase3
}

func (s *Store) TouchAlias(_ context.Context, _ int64, _ string) error {
	return ErrNotImplementedPhase3
}

func (s *Store) UnresolvedClaimViolationsForIssue(_ context.Context, _ int64, _ string, _ int) ([]db.ClaimViolationSummary, int64, error) {
	return nil, 0, ErrNotImplementedPhase3
}

func (s *Store) UnresolvedClaimViolationsForProject(_ context.Context, _ int64, _ int) ([]db.ClaimViolationSummary, int64, error) {
	return nil, 0, ErrNotImplementedPhase3
}

func (s *Store) UpdateOwner(_ context.Context, _ int64, _ *string, _ string) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) UpdatePriority(_ context.Context, _ int64, _ *int64, _ string) (db.Issue, *db.Event, bool, error) {
	return db.Issue{}, nil, false, ErrNotImplementedPhase3
}

func (s *Store) UpsertClaimCache(_ context.Context, _ db.IssueClaim) error {
	return ErrNotImplementedPhase3
}

func (s *Store) UpsertFederationBinding(_ context.Context, _ db.FederationBinding) (db.FederationBinding, error) {
	return db.FederationBinding{}, ErrNotImplementedPhase3
}

func (s *Store) UpsertImportMapping(_ context.Context, _ db.ImportMappingParams) (db.ImportMapping, error) {
	return db.ImportMapping{}, ErrNotImplementedPhase3
}
